Repository streamnative/pulsar-io-cloud-storage, pull requests merged in 2022-03, with the labels that each got.

#273 fix schema version format
  src/main/java/org/apache/pulsar/io/jcloud/util/MetadataUtil.java
  src/test/java/org/apache/pulsar/io/jcloud/MetadataUtilTest.java
Labels: type/enhancement

#285 fix cannot parse PROTOBUF_NATIVE schema
  src/main/java/org/apache/pulsar/io/jcloud/format/AvroFormat.java
  src/main/java/org/apache/pulsar/io/jcloud/format/ParquetFormat.java
  src/main/java/org/apache/pulsar/io/jcloud/util/AvroRecordUtil.java
Labels: type/enhancement, doc-info-missing

#311 [security] Upgrade vulnerable dependencies
  pom.xml
Labels: doc-info-missing

#312 [security] Upgrade jackson-databind to get rid of CVE-2020-36518
  pom.xml
Labels: no-need-doc
