Repository streamnative/pulsar-io-cloud-storage, pull requests merged in 2023-03, with the labels that each got.

#609 [feat][json] Allow NaN numbers when flag is set
  README.md
  docs/cloud-storage-sink.md
  src/main/java/org/apache/pulsar/io/jcloud/BlobStoreAbstractConfig.java
  src/main/java/org/apache/pulsar/io/jcloud/format/JsonFormat.java
Labels: doc

#610 [chore] Upgrade to JDK 17
  .github/workflows/pr-test.yml
  .github/workflows/release.yml
  pom.xml
Labels: no-need-doc

#617 Improve the uploaded logging
  src/main/java/org/apache/pulsar/io/jcloud/sink/BlobStoreAbstractSink.java
Labels: no-need-doc

#626 Fix JsonFormat convert failed when use array jsonBytes or jsonString.
  src/main/java/org/apache/pulsar/io/jcloud/format/JsonFormat.java
  src/test/java/org/apache/pulsar/io/jcloud/format/FormatTestBase.java
  src/test/java/org/apache/pulsar/io/jcloud/format/JsonFormatTest.java
Labels: type/bug, no-need-doc, release/2.10.2.5, release/2.10.3.7, release/2.11.0.5
